import { Lesson } from '../types';

export const LESSONS: Lesson[] = [
  {
    id: 1,
    title: 'Olá! Primeiros Contatos',
    titleEs: '¡Hola! Primeros Contactos',
    level: 'A0',
    description: 'Learn essential greetings and how to introduce yourself in Brazilian Portuguese.',
    estimatedMinutes: 10,
    phrases: [
      { portuguese: 'Olá!', spanish: '¡Hola!', phonetic: 'oh-LAH', example: 'Olá! Como vai?', nativeUsage: 'Universal greeting, used any time of day.' },
      { portuguese: 'Bom dia', spanish: 'Buenos días', phonetic: 'bohn JEE-ah', example: 'Bom dia, tudo bem?', nativeUsage: 'Used until about noon.' },
      { portuguese: 'Boa tarde', spanish: 'Buenas tardes', phonetic: 'BOH-ah TAR-jee', example: 'Boa tarde, como você está?', nativeUsage: 'Used from noon to sunset.' },
      { portuguese: 'Boa noite', spanish: 'Buenas noches', phonetic: 'BOH-ah NOY-chee', example: 'Boa noite a todos!', nativeUsage: 'Used after sunset, also means "good night" when leaving.' },
      { portuguese: 'Tudo bem?', spanish: '¿Todo bien?', phonetic: 'TOO-doh behn', example: '– Olá! Tudo bem? – Tudo bem, obrigado!', nativeUsage: 'The most common way to ask "how are you?" in Brazil.' },
      { portuguese: 'Tudo bom!', spanish: '¡Todo bien!', phonetic: 'TOO-doh bohn', example: 'Tudo bom, e você?', nativeUsage: 'Standard positive response.' },
      { portuguese: 'Meu nome é...', spanish: 'Mi nombre es...', phonetic: 'MEH-oo NOH-mee eh', example: 'Meu nome é Carlos.', nativeUsage: 'Formal introduction.' },
      { portuguese: 'Me chamo...', spanish: 'Me llamo...', phonetic: 'mee SHA-moh', example: 'Me chamo Ana.', nativeUsage: 'More casual: "I call myself..."' },
      { portuguese: 'Prazer!', spanish: '¡Mucho gusto!', phonetic: 'prah-ZEHR', example: 'Prazer em te conhecer!', nativeUsage: 'Said when meeting someone.' },
      { portuguese: 'Obrigado / Obrigada', spanish: 'Gracias', phonetic: 'oh-bree-GAH-doh/dah', example: 'Obrigado pela ajuda!', nativeUsage: 'Men say obrigado, women say obrigada.' },
      { portuguese: 'De nada', spanish: 'De nada', phonetic: 'jee NAH-dah', example: '– Obrigado! – De nada!', nativeUsage: '"You\'re welcome." Sounds almost the same as Spanish.' },
      { portuguese: 'Com licença', spanish: 'Con permiso / Disculpe', phonetic: 'kohn lee-SEN-sah', example: 'Com licença, posso passar?', nativeUsage: 'Used to excuse yourself or get someone\'s attention.' },
    ],
    grammar: {
      title: 'Ser vs. Estar — The Key Difference',
      explanation: 'Like Spanish, Portuguese has two "to be" verbs. "Ser" is for permanent traits; "estar" is for temporary states. In casual speech, Brazilians often use "estar" where Spanish speakers would too.',
      examples: [
        { portuguese: 'Eu sou brasileiro.', spanish: 'Yo soy brasileño.' },
        { portuguese: 'Eu estou cansado.', spanish: 'Yo estoy cansado.' },
        { portuguese: 'Ela é professora.', spanish: 'Ella es profesora.' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Olá! Tudo bem?', spanish: '¡Hola! ¿Todo bien?' },
      { speaker: 'B', portuguese: 'Tudo bem, obrigado! E você?', spanish: '¡Todo bien, gracias! ¿Y tú?' },
      { speaker: 'A', portuguese: 'Tudo ótimo! Me chamo Pedro. Qual é o seu nome?', spanish: '¡Todo excelente! Me llamo Pedro. ¿Cuál es tu nombre?' },
      { speaker: 'B', portuguese: 'Meu nome é Maria. Prazer!', spanish: 'Mi nombre es María. ¡Mucho gusto!' },
      { speaker: 'A', portuguese: 'Prazer também! De onde você é?', spanish: '¡Igualmente! ¿De dónde eres?' },
      { speaker: 'B', portuguese: 'Sou de São Paulo. E você?', spanish: 'Soy de São Paulo. ¿Y tú?' },
    ],
    pronunciationTips: [
      { sound: 'ã / ão', phonetic: 'nasal "an"', example: 'não → "naun"', tip: 'No equivalent in Spanish. Pinch your nose and say "an" — that nasal resonance is the sound.' },
      { sound: 'lh', phonetic: 'like "lh" in "million"', example: 'elho → "elho"', tip: 'Similar to Spanish "ll" in some dialects. Think "y" sound with your tongue on the palate.' },
      { sound: 'r (initial)', phonetic: 'like English "h"', example: 'Rio → "HEE-oh"', tip: 'Brazilian R at the start of a word sounds like an English H, not like Spanish R.' },
    ],
    quiz: [
      { question: 'How do you say "good morning" in Portuguese?', options: ['Boa noite', 'Bom dia', 'Boa tarde', 'Olá'], correct: 1, explanation: '"Bom dia" is used until noon, just like "buenos días" in Spanish.' },
      { question: 'A woman says "thank you." She should say:', options: ['Obrigado', 'Obrigada', 'De nada', 'Prazer'], correct: 1, explanation: 'In Portuguese, the ending changes by gender: obrigado (men), obrigada (women).' },
      { question: 'What does "Tudo bem?" mean?', options: ['What is your name?', 'Where are you from?', 'How are you?', 'Nice to meet you'], correct: 2, explanation: '"Tudo bem?" literally means "everything well?" — Brazil\'s most common greeting.' },
      { question: 'How do you introduce yourself casually?', options: ['Meu nome é...', 'Com licença...', 'Me chamo...', 'De nada...'], correct: 2, explanation: '"Me chamo..." is the casual way, like "me llamo" in Spanish.' },
    ],
    speakingChallenge: 'Record yourself greeting someone, saying your name, and asking where they are from — all in Portuguese!',
    vocabulary: [
      { word: 'olá', translation: 'hola' }, { word: 'obrigado', translation: 'gracias' },
      { word: 'prazer', translation: 'mucho gusto' }, { word: 'nome', translation: 'nombre' },
      { word: 'você', translation: 'tú/usted' }, { word: 'tudo', translation: 'todo' },
    ],
  },
  {
    id: 2,
    title: 'Números e Dinheiro',
    titleEs: 'Números y Dinero',
    level: 'A0',
    description: 'Master numbers 1–100 and essential money vocabulary for shopping and daily life.',
    estimatedMinutes: 12,
    phrases: [
      { portuguese: 'Quanto custa?', spanish: '¿Cuánto cuesta?', phonetic: 'KWAN-toh KOOSH-tah', example: 'Quanto custa esse vestido?', nativeUsage: 'The go-to phrase for asking prices.' },
      { portuguese: 'É muito caro', spanish: 'Es muy caro', phonetic: 'eh MOO-ee KAH-roh', example: 'R$200? É muito caro!', nativeUsage: 'Brazilians love to negotiate!' },
      { portuguese: 'Tem desconto?', spanish: '¿Tiene descuento?', phonetic: 'tehn desh-KOHN-toh', example: 'Tem desconto para estudantes?', nativeUsage: 'Always worth asking in markets.' },
      { portuguese: 'Pode parcelar?', spanish: '¿Se puede pagar en cuotas?', phonetic: 'POH-jee par-seh-LAR', example: 'Pode parcelar em 3 vezes?', nativeUsage: 'Installment payments are extremely common in Brazil.' },
      { portuguese: 'Vou levar', spanish: 'Me lo llevo', phonetic: 'voh leh-VAR', example: 'Tá bom, vou levar!', nativeUsage: '"I\'ll take it" — used when buying something.' },
      { portuguese: 'Troco', spanish: 'Cambio / Vuelto', phonetic: 'TROH-koh', example: 'Aqui está o troco.', nativeUsage: 'The change you get back.' },
      { portuguese: 'Cartão ou dinheiro?', spanish: '¿Tarjeta o efectivo?', phonetic: 'kar-TAUN oo jee-NYEH-roh', example: 'Cartão ou dinheiro? Aceita Pix?', nativeUsage: 'Pix is Brazil\'s instant payment system — very common.' },
    ],
    grammar: {
      title: 'Gender of Numbers and Currency',
      explanation: 'Numbers in Portuguese are mostly the same as Spanish but with key differences in pronunciation. "Real" (pl: reais) is Brazilian currency. Note: "um/uma" (one) agrees in gender.',
      examples: [
        { portuguese: 'Um real, dois reais', spanish: 'Un real, dos reales' },
        { portuguese: 'Vinte e um anos', spanish: 'Veintiún años' },
        { portuguese: 'Cem reais / cem pessoas', spanish: 'Cien reales / cien personas' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Com licença, quanto custa essa camisa?', spanish: 'Disculpe, ¿cuánto cuesta esa camisa?' },
      { speaker: 'B', portuguese: 'Custa oitenta reais.', spanish: 'Cuesta ochenta reales.' },
      { speaker: 'A', portuguese: 'Nossa! É muito caro. Tem desconto?', spanish: '¡Vaya! Es muy caro. ¿Tiene descuento?' },
      { speaker: 'B', portuguese: 'Posso fazer por sessenta e cinco.', spanish: 'Puedo hacerlo por sesenta y cinco.' },
      { speaker: 'A', portuguese: 'Tá bom! Aceita cartão?', spanish: '¡De acuerdo! ¿Acepta tarjeta?' },
      { speaker: 'B', portuguese: 'Aceito sim. Débito ou crédito?', spanish: 'Sí, acepto. ¿Débito o crédito?' },
    ],
    pronunciationTips: [
      { sound: 'oi', phonetic: '"oy" sound', example: 'oitenta → "oy-TEN-tah"', tip: 'The "oi" diphthong sounds like English "boy". Common in numbers like oito (8).' },
      { sound: 'ei', phonetic: '"ay" sound', example: 'seis → "saysh"', tip: 'The "ei" sounds like English "hey". Note the final "s" is soft, like "sh".' },
      { sound: 'ss / ç', phonetic: '"ss" sharp', example: 'cinco → "SEEN-koh"', tip: 'The "c" before "i" and "e" sounds like "s", just like in Spanish.' },
    ],
    quiz: [
      { question: 'How do you ask "How much does it cost?"', options: ['Quanto tempo?', 'Quanto custa?', 'Onde fica?', 'Como vai?'], correct: 1, explanation: '"Quanto custa?" is the direct equivalent of "¿Cuánto cuesta?"' },
      { question: 'What is Brazil\'s instant payment system?', options: ['Cartão', 'Troco', 'Pix', 'Parcelar'], correct: 2, explanation: 'Pix is Brazil\'s widely used instant payment platform, launched in 2020.' },
      { question: 'How do you say "I\'ll take it" in Portuguese?', options: ['Vou sair', 'Vou levar', 'Vou pagar', 'Vou ver'], correct: 1, explanation: '"Vou levar" literally means "I\'m going to take" — the standard phrase for buying.' },
      { question: 'What does "troco" mean?', options: ['Price', 'Discount', 'Change (money back)', 'Installment'], correct: 2, explanation: '"Troco" means the change you receive after paying, like "vuelto" in Spanish.' },
    ],
    speakingChallenge: 'Count from 1 to 20 in Portuguese, then say the price of three items in your home.',
    vocabulary: [
      { word: 'dinheiro', translation: 'dinero' }, { word: 'caro', translation: 'caro' },
      { word: 'barato', translation: 'barato' }, { word: 'desconto', translation: 'descuento' },
      { word: 'preço', translation: 'precio' }, { word: 'comprar', translation: 'comprar' },
    ],
  },
  {
    id: 3,
    title: 'Pedindo Comida',
    titleEs: 'Pidiendo Comida',
    level: 'A1',
    description: 'Navigate Brazilian restaurants and cafés with confidence.',
    estimatedMinutes: 15,
    phrases: [
      { portuguese: 'Uma mesa para dois, por favor', spanish: 'Una mesa para dos, por favor', phonetic: 'OO-mah MEH-zah PAH-rah doysh', example: 'Boa noite! Uma mesa para dois, por favor.', nativeUsage: 'How to request a table at a restaurant.' },
      { portuguese: 'O cardápio, por favor', spanish: 'El menú, por favor', phonetic: 'oh kar-DAH-pee-oh', example: 'Pode me trazer o cardápio?', nativeUsage: '"Cardápio" is the Brazilian word for menu (not "menú").' },
      { portuguese: 'Vou querer...', spanish: 'Voy a querer... / Quisiera...', phonetic: 'voh keh-REHR', example: 'Vou querer o frango grelhado, por favor.', nativeUsage: 'The natural way to order in Brazil — more polite than "quero."' },
      { portuguese: 'Está incluído o serviço?', spanish: '¿Está incluido el servicio?', phonetic: 'esh-TAH een-kloo-EE-doh', example: 'A gorjeta está incluída no serviço?', nativeUsage: '10% service charge is common in Brazilian restaurants.' },
      { portuguese: 'A conta, por favor', spanish: 'La cuenta, por favor', phonetic: 'ah KOHN-tah', example: 'Com licença, pode trazer a conta?', nativeUsage: 'Ask for the bill. "Conta" is bill/check (not "cuenta").' },
      { portuguese: 'Sem carne / sou vegetariano', spanish: 'Sin carne / soy vegetariano', phonetic: 'sehn KAR-nee', example: 'Sou vegetariano. Tem opções sem carne?', nativeUsage: 'Vegetarian options are increasingly common in Brazil.' },
      { portuguese: 'Tá gostoso!', spanish: '¡Está delicioso!', phonetic: 'tah gosh-TOH-zoh', example: 'Nossa, tá muito gostoso!', nativeUsage: '"Gostoso" means delicious. A huge compliment to the cook!' },
      { portuguese: 'Mais um, por favor', spanish: 'Otro/Uno más, por favor', phonetic: 'maysh oohn', example: 'Mais uma cerveja, por favor.', nativeUsage: 'Use "mais" to ask for another of anything.' },
    ],
    grammar: {
      title: 'Falso Amigo Alert: Polite False Cognates',
      explanation: 'Some words look like Spanish but mean different things! "Borracha" means rubber (not drunk woman). "Polvo" means octopus (not dust). "Exquisito" doesn\'t exist — "esquisito" means weird, not exquisite!',
      examples: [
        { portuguese: 'O polvo está gostoso.', spanish: 'El pulpo está delicioso.' },
        { portuguese: 'Isso é esquisito!', spanish: '¡Eso es raro/extraño!' },
        { portuguese: 'A borracha caiu.', spanish: 'La goma cayó.' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Boa tarde! Uma mesa para dois, por favor.', spanish: '¡Buenas tardes! Una mesa para dos, por favor.' },
      { speaker: 'B', portuguese: 'Claro! Por aqui, por favor. O cardápio.', spanish: '¡Claro! Por aquí, por favor. El menú.' },
      { speaker: 'A', portuguese: 'Obrigado. O que você recomenda?', spanish: 'Gracias. ¿Qué recomienda?' },
      { speaker: 'B', portuguese: 'A feijoada é ótima hoje!', spanish: '¡La feijoada está excelente hoy!' },
      { speaker: 'A', portuguese: 'Vou querer a feijoada e um suco de laranja.', spanish: 'Voy a querer la feijoada y un jugo de naranja.' },
      { speaker: 'B', portuguese: 'Ótima escolha! Vai querer sobremesa?', spanish: '¡Excelente elección! ¿Va a querer postre?' },
    ],
    pronunciationTips: [
      { sound: 'ão (nasal)', phonetic: '"aun" nasal', example: 'pão → "paun"', tip: 'The bread! "Pão" rhymes with "down" but nasalized. Practice: irmão, mão, não.' },
      { sound: 'lh', phonetic: 'like "lh" in "million"', example: 'alho → "AH-lyoh"', tip: 'Garlic = alho. The "lh" is like a soft "ly" sound — palate touches behind teeth.' },
      { sound: 'nh', phonetic: 'like Spanish "ñ"', example: 'vinho → "VEEN-yoh"', tip: '"Nh" = Spanish ñ. Vinho (wine), banho (bath),anha (gains).' },
    ],
    quiz: [
      { question: 'What is "cardápio" in English?', options: ['Bill', 'Menu', 'Tip', 'Receipt'], correct: 1, explanation: '"Cardápio" is the Brazilian Portuguese word for menu. "Menú" isn\'t used.' },
      { question: 'How do Brazilians politely say "I\'ll have..."?', options: ['Quero...', 'Dê-me...', 'Vou querer...', 'Preciso de...'], correct: 2, explanation: '"Vou querer" is softer and more natural than "quero" when ordering food.' },
      { question: 'What does "gostoso" mean?', options: ['Strange', 'Expensive', 'Delicious', 'Hungry'], correct: 2, explanation: '"Gostoso/gostosa" means delicious or tasty — a key word for enjoying Brazilian food!' },
      { question: '"Polvo" in Portuguese means:', options: ['Dust', 'Chicken', 'Octopus', 'Pepper'], correct: 2, explanation: 'False cognate alert! "Polvo" = octopus. Dust is "poeira." This trips up many Spanish speakers.' },
    ],
    speakingChallenge: 'Imagine you\'re at a churrascaria. Order a full meal in Portuguese: entry, main dish, drink, and ask for the bill.',
    vocabulary: [
      { word: 'comida', translation: 'comida' }, { word: 'cardápio', translation: 'menú' },
      { word: 'conta', translation: 'cuenta' }, { word: 'gostoso', translation: 'delicioso' },
      { word: 'frango', translation: 'pollo' }, { word: 'pão', translation: 'pan' },
    ],
  },
  {
    id: 4,
    title: 'Transporte e Direções',
    titleEs: 'Transporte y Direcciones',
    level: 'A1',
    description: 'Get around Brazilian cities — ask for directions and use public transport.',
    estimatedMinutes: 12,
    phrases: [
      { portuguese: 'Onde fica...?', spanish: '¿Dónde queda...?', phonetic: 'OHN-jee FEE-kah', example: 'Onde fica o metrô?', nativeUsage: '"Ficar" means to be located. "Onde fica?" is the standard way to ask where something is.' },
      { portuguese: 'Como chego até...?', spanish: '¿Cómo llego hasta...?', phonetic: 'KOH-moh SHEH-goh', example: 'Como chego até o centro?', nativeUsage: 'Ask for directions to get somewhere.' },
      { portuguese: 'Vire à direita / esquerda', spanish: 'Gire a la derecha / izquierda', phonetic: 'VEE-ree ah jee-RAY-tah', example: 'Vire à direita no semáforo.', nativeUsage: 'Directional instructions.' },
      { portuguese: 'Siga em frente', spanish: 'Siga recto / derecho', phonetic: 'SEE-gah ehn FREHN-chee', example: 'Siga em frente por dois quarteirões.', nativeUsage: '"Keep going straight."' },
      { portuguese: 'Fica longe?', spanish: '¿Queda lejos?', phonetic: 'FEE-kah LOHN-jee', example: '– Onde fica a praia? – Não fica longe!', nativeUsage: 'Ask if something is far away.' },
      { portuguese: 'Ponto de ônibus', spanish: 'Parada de autobús', phonetic: 'POHN-toh jee OH-nee-boosh', example: 'Qual é o ponto de ônibus mais próximo?', nativeUsage: 'Bus stop. "Ônibus" = bus in Brazil.' },
      { portuguese: 'Quanto tempo demora?', spanish: '¿Cuánto tiempo tarda?', phonetic: 'KWAN-toh TEHM-poh jeh-MOH-rah', example: 'Quanto tempo demora de metrô?', nativeUsage: 'Ask how long it takes.' },
    ],
    grammar: {
      title: 'Using "Ficar" for Location',
      explanation: '"Ficar" in Brazilian Portuguese is used for location (where things are), which Spanish uses "quedar" or "estar." This is one of the most important differences you\'ll encounter daily.',
      examples: [
        { portuguese: 'O banco fica na esquina.', spanish: 'El banco queda en la esquina.' },
        { portuguese: 'Onde fica o banheiro?', spanish: '¿Dónde está el baño?' },
        { portuguese: 'Fica perto do metrô.', spanish: 'Queda cerca del metro.' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Com licença! Como chego até a Avenida Paulista?', spanish: '¡Disculpe! ¿Cómo llego hasta la Avenida Paulista?' },
      { speaker: 'B', portuguese: 'Siga em frente e vire à esquerda no semáforo.', spanish: 'Siga recto y gire a la izquierda en el semáforo.' },
      { speaker: 'A', portuguese: 'Fica longe daqui?', spanish: '¿Queda lejos de aquí?' },
      { speaker: 'B', portuguese: 'Uns dez minutos a pé.', spanish: 'Unos diez minutos caminando.' },
      { speaker: 'A', portuguese: 'Obrigado! Tem metrô por aqui?', spanish: '¡Gracias! ¿Hay metro por aquí?' },
      { speaker: 'B', portuguese: 'Tem sim! O metrô fica a duas quadras.', spanish: '¡Sí hay! El metro queda a dos cuadras.' },
    ],
    pronunciationTips: [
      { sound: 'ônibus', phonetic: '"OH-nee-boosh"', example: 'ônibus → bus', tip: 'The final "s" in Brazilian Portuguese often sounds like "sh". Practice: nós, vós, mais.' },
      { sound: 'quadra', phonetic: '"KWAH-drah"', example: 'quadra → block', tip: '"Quadra" means city block. The "qu" before "a" sounds like "kw" — similar to Spanish.' },
    ],
    quiz: [
      { question: 'How do you ask "Where is the subway?"', options: ['Como fica o metrô?', 'Onde fica o metrô?', 'Quando fica o metrô?', 'Por que fica o metrô?'], correct: 1, explanation: '"Onde fica...?" is how Brazilians ask where something is located.' },
      { question: 'What does "Siga em frente" mean?', options: ['Turn right', 'Turn left', 'Go straight', 'Go back'], correct: 2, explanation: '"Siga em frente" = keep going straight, like "siga derecho" in Spanish.' },
      { question: 'The bus in Brazil is called:', options: ['Autobús', 'Camión', 'Ônibus', 'Micro'], correct: 2, explanation: '"Ônibus" is the Brazilian word for bus. Note the nasal vowel at the start!' },
    ],
    speakingChallenge: 'Give directions from your home to the nearest supermarket, entirely in Portuguese.',
    vocabulary: [
      { word: 'ônibus', translation: 'autobús' }, { word: 'metrô', translation: 'metro' },
      { word: 'direita', translation: 'derecha' }, { word: 'esquerda', translation: 'izquierda' },
      { word: 'perto', translation: 'cerca' }, { word: 'longe', translation: 'lejos' },
    ],
  },
  {
    id: 5,
    title: 'Família e Pessoas',
    titleEs: 'Familia y Personas',
    level: 'A1',
    description: 'Talk about your family, describe people, and discuss relationships.',
    estimatedMinutes: 12,
    phrases: [
      { portuguese: 'Minha família', spanish: 'Mi familia', phonetic: 'MEE-nyah fah-MEE-lyah', example: 'Minha família é grande.', nativeUsage: 'Possessives agree in gender with the noun, not the owner.' },
      { portuguese: 'Tenho um irmão / uma irmã', spanish: 'Tengo un hermano / una hermana', phonetic: 'TEN-yoh', example: 'Tenho dois irmãos e uma irmã.', nativeUsage: '"Irmão" (brother), "irmã" (sister) — note the nasal ending.' },
      { portuguese: 'Sou casado/a', spanish: 'Soy casado/a', phonetic: 'soh kah-ZAH-doh', example: 'Sou casada há cinco anos.', nativeUsage: 'Marital status.' },
      { portuguese: 'Meu marido / Minha esposa', spanish: 'Mi marido / Mi esposa', phonetic: 'MEH-oo mah-REE-doh', example: 'Meu marido se chama João.', nativeUsage: '"Marido" (husband), "esposa" (wife) — same as Spanish.' },
      { portuguese: 'Tenho filhos?', spanish: '¿Tienes hijos?', phonetic: 'TEN-yoh FEEL-yoosh', example: 'Você tem filhos?', nativeUsage: '"Filhos" = children/sons. "Filha" = daughter.' },
      { portuguese: 'É meu / minha amigo/a', spanish: 'Es mi amigo/a', phonetic: 'eh MEH-oo ah-MEE-goh', example: 'Esse é meu melhor amigo.', nativeUsage: 'Introducing a friend.' },
    ],
    grammar: {
      title: 'Possessive Adjectives',
      explanation: 'Portuguese possessives are very similar to Spanish but Brazilians often drop the article before them in casual speech.',
      examples: [
        { portuguese: 'Meu pai / Minha mãe', spanish: 'Mi padre / Mi madre' },
        { portuguese: 'Nosso apartamento', spanish: 'Nuestro apartamento' },
        { portuguese: 'A casa dela (dela = her)', spanish: 'Su casa (de ella)' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Você tem família grande?', spanish: '¿Tienes familia grande?' },
      { speaker: 'B', portuguese: 'Sim! Tenho três irmãos e uma irmã.', spanish: '¡Sí! Tengo tres hermanos y una hermana.' },
      { speaker: 'A', portuguese: 'Nossa! E seus pais moram com você?', spanish: '¡Vaya! ¿Y tus padres viven contigo?' },
      { speaker: 'B', portuguese: 'Não, eles moram em Curitiba. Sou casado e tenho dois filhos.', spanish: 'No, ellos viven en Curitiba. Estoy casado y tengo dos hijos.' },
      { speaker: 'A', portuguese: 'Que legal! Quantos anos eles têm?', spanish: '¡Qué bueno! ¿Cuántos años tienen?' },
    ],
    pronunciationTips: [
      { sound: 'ão (plural)', phonetic: '"aun-sh"', example: 'irmãos → "eer-MAUN-sh"', tip: 'Plural of -ão words is -ãos. The nasal sound + final s. Practice: mãos (hands), pães (breads).' },
      { sound: 'lh in filha', phonetic: '"FEEL-yah"', example: 'filha → daughter', tip: '"Filha" — the lh sounds like the "lli" in "million." Relax your tongue on the palate.' },
    ],
    quiz: [
      { question: 'How do you say "sister" in Portuguese?', options: ['Irmão', 'Irmã', 'Esposa', 'Filha'], correct: 1, explanation: '"Irmã" is sister, "irmão" is brother. Note the nasal -ã ending for the feminine.' },
      { question: '"Filhos" means:', options: ['Parents', 'Siblings', 'Children/Sons', 'Friends'], correct: 2, explanation: '"Filhos" = children (or sons). "Filha" = daughter. From Latin "filius."' },
      { question: 'How do you say "my wife"?', options: ['Meu marido', 'Minha esposa', 'Minha filha', 'Meu irmão'], correct: 1, explanation: '"Esposa" is wife — same as Spanish! "Minha" is used because "esposa" is feminine.' },
    ],
    speakingChallenge: 'Describe your family in 5 sentences — ages, names, where they live. All in Portuguese!',
    vocabulary: [
      { word: 'família', translation: 'familia' }, { word: 'irmão', translation: 'hermano' },
      { word: 'irmã', translation: 'hermana' }, { word: 'pai', translation: 'padre' },
      { word: 'mãe', translation: 'madre' }, { word: 'filho', translation: 'hijo' },
    ],
  },
  {
    id: 6,
    title: 'Trabalho e Rotina',
    titleEs: 'Trabajo y Rutina',
    level: 'A1',
    description: 'Talk about your job, daily schedule, and common workplace interactions.',
    estimatedMinutes: 14,
    phrases: [
      { portuguese: 'Em que você trabalha?', spanish: '¿En qué trabajas?', phonetic: 'ehn kee voh-SEH trah-BAH-lyah', example: 'Em que você trabalha?', nativeUsage: 'Asking about someone\'s job.' },
      { portuguese: 'Sou engenheiro / médico', spanish: 'Soy ingeniero / médico', phonetic: 'soh ehn-jeh-NYEH-roh', example: 'Sou engenheiro de software.', nativeUsage: 'State your profession. Many professions are cognates!' },
      { portuguese: 'Trabalho de casa', spanish: 'Trabajo desde casa', phonetic: 'trah-BAH-lyoh jee KAH-zah', example: 'Agora trabalho de casa.', nativeUsage: 'Working from home — extremely common post-2020.' },
      { portuguese: 'Minha rotina começa às...', spanish: 'Mi rutina empieza a las...', phonetic: 'ROH-chee-nah koh-MEH-sah', example: 'Minha rotina começa às sete da manhã.', nativeUsage: 'Describing your morning routine.' },
      { portuguese: 'Tenho uma reunião', spanish: 'Tengo una reunión', phonetic: 'reh-oo-nee-AUN', example: 'Às três tenho uma reunião importante.', nativeUsage: '"Reunião" = meeting. Note the nasal ending -ão.' },
      { portuguese: 'Estou ocupado/a', spanish: 'Estoy ocupado/a', phonetic: 'esh-TOH oh-koo-PAH-doh', example: 'Desculpa, estou muito ocupada agora.', nativeUsage: '"I\'m busy." Essential for polite excuses.' },
    ],
    grammar: {
      title: 'Present Tense — Regular Verbs',
      explanation: 'Portuguese present tense for regular verbs follows similar patterns to Spanish. The -AR verbs conjugate with endings: -o, -a, -amos, -am. The big difference: no "vosotros" form — Brazilians use "vocês" instead.',
      examples: [
        { portuguese: 'Eu trabalho / você trabalha', spanish: 'Yo trabajo / tú trabajas' },
        { portuguese: 'Nós trabalhamos / vocês trabalham', spanish: 'Nosotros trabajamos / vosotros trabajáis' },
        { portuguese: 'Ela come / eles comem', spanish: 'Ella come / ellos comen' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Em que você trabalha?', spanish: '¿En qué trabajas?' },
      { speaker: 'B', portuguese: 'Sou designer. Trabalho de casa. E você?', spanish: 'Soy diseñador. Trabajo desde casa. ¿Y tú?' },
      { speaker: 'A', portuguese: 'Sou professor. Trabalho numa escola perto daqui.', spanish: 'Soy profesor. Trabajo en una escuela cerca de aquí.' },
      { speaker: 'B', portuguese: 'Legal! Você gosta do seu trabalho?', spanish: '¡Bueno! ¿Te gusta tu trabajo?' },
      { speaker: 'A', portuguese: 'Gosto sim, mas às vezes é cansativo.', spanish: 'Sí me gusta, pero a veces es cansado.' },
    ],
    pronunciationTips: [
      { sound: 'trabalho', phonetic: '"trah-BAH-lyoh"', example: 'trabalho → work', tip: 'The "lh" in "trabalho" is the same palatal sound as in "filho." Practice these together.' },
      { sound: 'reunião', phonetic: '"heh-oo-nee-AUN"', example: 'reunião → meeting', tip: 'Three vowels in a row! Re-u-ni-ão. Stress on the last syllable. The ão is nasal.' },
    ],
    quiz: [
      { question: 'How do you ask "What do you do for work?"', options: ['Onde você trabalha?', 'Em que você trabalha?', 'Por que você trabalha?', 'Quando você trabalha?'], correct: 1, explanation: '"Em que você trabalha?" = "¿En qué trabajas?" A very natural way to ask about someone\'s job.' },
      { question: 'How do you say "I have a meeting"?', options: ['Tenho uma palestra', 'Tenho uma festa', 'Tenho uma reunião', 'Tenho uma viagem'], correct: 2, explanation: '"Reunião" = meeting/reunion. The -ão ending is characteristic of many Portuguese nouns.' },
      { question: 'In Brazilian Portuguese, "you all" is:', options: ['Vosotros', 'Ustedes', 'Vocês', 'Eles'], correct: 2, explanation: '"Vocês" is the Brazilian plural "you." Unlike Spain, Brazil dropped "vós" from everyday speech.' },
    ],
    speakingChallenge: 'Describe your typical workday from morning to evening in Portuguese. Use at least 6 sentences.',
    vocabulary: [
      { word: 'trabalho', translation: 'trabajo' }, { word: 'reunião', translation: 'reunión' },
      { word: 'ocupado', translation: 'ocupado' }, { word: 'manhã', translation: 'mañana' },
      { word: 'tarde', translation: 'tarde' }, { word: 'rotina', translation: 'rutina' },
    ],
  },
  {
    id: 7,
    title: 'Saúde e Corpo',
    titleEs: 'Salud y Cuerpo',
    level: 'A2',
    description: 'Talk about health, body parts, symptoms, and visit a pharmacy or doctor.',
    estimatedMinutes: 14,
    phrases: [
      { portuguese: 'Não estou me sentindo bem', spanish: 'No me estoy sintiendo bien', phonetic: 'naun esh-TOH mee sehn-CHIN-doh behn', example: 'Hoje não estou me sentindo bem.', nativeUsage: 'The most common way to say you feel sick.' },
      { portuguese: 'Estou com febre', spanish: 'Tengo fiebre', phonetic: 'esh-TOH kohn FEH-bree', example: 'Estou com 38 de febre.', nativeUsage: 'Note: Brazilians say "estou com febre" (I\'m with fever), not "tenho febre."' },
      { portuguese: 'Dói muito', spanish: 'Duele mucho', phonetic: 'DOY MOO-ee-toh', example: 'Minha cabeça dói muito.', nativeUsage: '"Doer" = to hurt/ache. "Dói" is third person singular.' },
      { portuguese: 'Preciso de um médico', spanish: 'Necesito un médico', phonetic: 'preh-SEE-zoh jee oohn MEH-jee-koh', example: 'Preciso de um médico urgente!', nativeUsage: '"Precisar de" = to need. Always followed by "de."' },
      { portuguese: 'Farmácia', spanish: 'Farmacia', phonetic: 'far-MAH-see-ah', example: 'Tem uma farmácia perto daqui?', nativeUsage: 'Pharmacies in Brazil are very accessible and pharmacists can suggest medicines.' },
      { portuguese: 'Remédio / Medicamento', spanish: 'Remedio / Medicamento', phonetic: 'heh-MEH-jee-oh', example: 'Tem remédio para dor de cabeça?', nativeUsage: '"Remédio" is the everyday word; "medicamento" is more formal.' },
    ],
    grammar: {
      title: '"Estar com" vs. "Ter" for Conditions',
      explanation: 'One of the biggest differences from Spanish: in Brazilian Portuguese, physical conditions use "estar com" (to be with), NOT "ter" (to have). Spanish uses "tener" for these, but Portuguese uses "estar com."',
      examples: [
        { portuguese: 'Estou com fome. (I\'m hungry)', spanish: 'Tengo hambre.' },
        { portuguese: 'Estou com sede. (I\'m thirsty)', spanish: 'Tengo sed.' },
        { portuguese: 'Estou com frio. (I\'m cold)', spanish: 'Tengo frío.' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Bom dia. Não estou me sentindo bem.', spanish: 'Buenos días. No me estoy sintiendo bien.' },
      { speaker: 'B', portuguese: 'Me desculpe. Quais são seus sintomas?', spanish: 'Lo siento. ¿Cuáles son sus síntomas?' },
      { speaker: 'A', portuguese: 'Estou com febre e dor de cabeça.', spanish: 'Tengo fiebre y dolor de cabeza.' },
      { speaker: 'B', portuguese: 'Desde quando você está assim?', spanish: '¿Desde cuándo está así?' },
      { speaker: 'A', portuguese: 'Desde ontem à noite.', spanish: 'Desde anoche.' },
      { speaker: 'B', portuguese: 'Vou receitar um remédio. Tome a cada 8 horas.', spanish: 'Voy a recetarle un medicamento. Tómelo cada 8 horas.' },
    ],
    pronunciationTips: [
      { sound: 'dói', phonetic: '"DOY"', example: 'dói → hurts', tip: 'The "ói" diphthong sounds like English "boy." Dói (hurts), boi (ox), herói (hero).' },
      { sound: 'febre', phonetic: '"FEH-bree"', example: 'febre → fever', tip: 'Final "e" in Portuguese often sounds like "ee" (like "eh-ee"). Practice: leite, monte, noite.' },
    ],
    quiz: [
      { question: 'How do Brazilians say "I\'m hungry"?', options: ['Tenho fome', 'Estou com fome', 'Sou com fome', 'Tenho faminto'], correct: 1, explanation: '"Estou com fome" is correct. Brazilians use "estar com" for physical states, unlike Spanish "tener."' },
      { question: 'What is the everyday word for medicine in Brazil?', options: ['Medicação', 'Medicamento', 'Remédio', 'Droga'], correct: 2, explanation: '"Remédio" is the common word. "Medicamento" is more formal/clinical.' },
      { question: '"Dói muito" means:', options: ['It costs a lot', 'It hurts a lot', 'It\'s very far', 'It\'s very late'], correct: 1, explanation: '"Doer" = to hurt/ache. "Dói muito" = hurts a lot. Related to Spanish "doler."' },
    ],
    speakingChallenge: 'Role-play a visit to the pharmacy. Describe your symptoms and ask for a recommendation.',
    vocabulary: [
      { word: 'saúde', translation: 'salud' }, { word: 'doente', translation: 'enfermo' },
      { word: 'febre', translation: 'fiebre' }, { word: 'dor', translation: 'dolor' },
      { word: 'farmácia', translation: 'farmacia' }, { word: 'remédio', translation: 'remedio' },
    ],
  },
  {
    id: 8,
    title: 'Tempo Livre e Hobbies',
    titleEs: 'Tiempo Libre y Pasatiempos',
    level: 'A2',
    description: 'Discuss hobbies, free time activities, and make plans with friends.',
    estimatedMinutes: 13,
    phrases: [
      { portuguese: 'Nas horas vagas...', spanish: 'En mi tiempo libre...', phonetic: 'naz OH-raz VAH-gahsh', example: 'Nas horas vagas gosto de correr.', nativeUsage: '"Nas horas vagas" = in free hours. Very natural Brazilian expression.' },
      { portuguese: 'Curto muito...', spanish: 'Me gusta mucho...', phonetic: 'KOOR-toh MOO-ee-toh', example: 'Curto muito ouvir música.', nativeUsage: '"Curtir" is Brazilian slang for to like/enjoy. Very casual and common.' },
      { portuguese: 'Que saudade!', spanish: '¡Cuánto lo echo de menos! / ¡Qué nostalgia!', phonetic: 'kee sow-DAH-jee', example: 'Que saudade de você!', nativeUsage: '"Saudade" — Portuguese\'s most famous untranslatable word. A longing for something/someone.' },
      { portuguese: 'Vamos sair?', spanish: '¿Salimos?', phonetic: 'VAH-mohsh sah-EER', example: 'Vamos sair hoje à noite?', nativeUsage: 'Inviting someone out.' },
      { portuguese: 'Que horas você está livre?', spanish: '¿A qué hora estás libre?', phonetic: 'kee OH-rahsh esh-TAH LEE-vree', example: 'Que horas você está livre amanhã?', nativeUsage: 'Scheduling and making plans.' },
      { portuguese: 'Topei! / Combinado!', spanish: '¡De acuerdo! / ¡Trato hecho!', phonetic: 'toh-PAY / kohm-bee-NAH-doh', example: '– Vamos ao cinema? – Topei!', nativeUsage: '"Topei" = I\'m in! "Combinado" = agreed/it\'s a deal. Both very Brazilian.' },
    ],
    grammar: {
      title: 'Gerunds — The "-ndo" Form',
      explanation: 'Portuguese gerunds are used much more than in Spanish for ongoing actions. Brazilians commonly use "estar + gerund" for present continuous. You\'ll hear this constantly!',
      examples: [
        { portuguese: 'Estou ouvindo música.', spanish: 'Estoy escuchando música.' },
        { portuguese: 'Estamos saindo agora.', spanish: 'Estamos saliendo ahora.' },
        { portuguese: 'Ela está fazendo a janta.', spanish: 'Ella está haciendo la cena.' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'O que você faz nas horas vagas?', spanish: '¿Qué haces en tu tiempo libre?' },
      { speaker: 'B', portuguese: 'Curto muito jogar futebol e ouvir música. E você?', spanish: 'Me gusta mucho jugar fútbol y escuchar música. ¿Y tú?' },
      { speaker: 'A', portuguese: 'Gosto de ler e cozinhar. Vamos sair esse fim de semana?', spanish: 'Me gusta leer y cocinar. ¿Salimos este fin de semana?' },
      { speaker: 'B', portuguese: 'Combinado! Que tal sábado à noite?', spanish: '¡De acuerdo! ¿Qué tal el sábado por la noche?' },
      { speaker: 'A', portuguese: 'Perfeito! Topei.', spanish: '¡Perfecto! Estoy dentro.' },
    ],
    pronunciationTips: [
      { sound: 'saudade', phonetic: '"sow-DAH-jee"', example: 'saudade → longing', tip: 'Brazil\'s most famous word! The "au" sounds like "ow" in "cow." The final "de" is soft like "jee."' },
      { sound: 'horas vagas', phonetic: '"OH-rahsh VAH-gahsh"', example: 'free time', tip: 'Final "s" before a vowel connects smoothly. Final "s" at word end = "sh" sound in Brazilian.' },
    ],
    quiz: [
      { question: '"Curtir" in Brazilian slang means:', options: ['To run', 'To like/enjoy', 'To buy', 'To travel'], correct: 1, explanation: '"Curtir" is colloquial Brazilian for to enjoy/like. It\'s also the word for "liking" on social media.' },
      { question: '"Topei!" means:', options: ['I refused', 'I\'m tired', 'I\'m in / Agreed!', 'I don\'t know'], correct: 2, explanation: '"Topei!" comes from "topar" = to agree. It\'s enthusiastic acceptance, like "I\'m in!"' },
      { question: '"Saudade" is best described as:', options: ['Happiness', 'Anger', 'A longing/nostalgic feeling', 'Surprise'], correct: 2, explanation: '"Saudade" is untranslatable — a bittersweet longing for someone or something you miss.' },
    ],
    speakingChallenge: 'Invite a friend out for the weekend. Suggest an activity, agree on a time and place — all in Portuguese!',
    vocabulary: [
      { word: 'curtir', translation: 'disfrutar/gustar' }, { word: 'saudade', translation: 'nostalgia/añoranza' },
      { word: 'fim de semana', translation: 'fin de semana' }, { word: 'sair', translation: 'salir' },
      { word: 'música', translation: 'música' }, { word: 'combinado', translation: 'de acuerdo' },
    ],
  },
  {
    id: 9,
    title: 'Opiniões e Discussões',
    titleEs: 'Opiniones y Discusiones',
    level: 'A2',
    description: 'Express opinions, agree, disagree, and have meaningful conversations in Portuguese.',
    estimatedMinutes: 15,
    phrases: [
      { portuguese: 'Na minha opinião...', spanish: 'En mi opinión...', phonetic: 'nah MEE-nyah oh-peen-YAUN', example: 'Na minha opinião, isso é muito importante.', nativeUsage: 'Formal way to express opinion.' },
      { portuguese: 'Acho que...', spanish: 'Creo que...', phonetic: 'AH-shoh kee', example: 'Acho que ela tem razão.', nativeUsage: '"Achar" = to think/believe. The most common opinion marker in Brazil.' },
      { portuguese: 'Concordo / Discordo', spanish: 'De acuerdo / En desacuerdo', phonetic: 'kohn-KOR-doh / jeesh-KOR-doh', example: 'Concordo com você.', nativeUsage: 'Agree/Disagree — similar to Spanish.' },
      { portuguese: 'Tem razão', spanish: 'Tiene razón', phonetic: 'tehn hah-ZAUN', example: 'Você tem razão nisso.', nativeUsage: '"You\'re right." The "r" here sounds like an English H.' },
      { portuguese: 'Depende', spanish: 'Depende', phonetic: 'jeh-PEHN-jee', example: 'Depende da situação.', nativeUsage: 'Very common response — "it depends."' },
      { portuguese: 'Com certeza', spanish: 'Con certeza / Por supuesto', phonetic: 'kohn ser-TEH-zah', example: 'Com certeza vai dar certo!', nativeUsage: '"Absolutely / certainly." Very common in affirmations.' },
    ],
    grammar: {
      title: 'Subjunctive After "Achar Que" and Opinion Verbs',
      explanation: 'When expressing doubt or opinion in negative form, Portuguese uses the subjunctive — just like Spanish, but slightly more consistently. "Acho que" takes indicative; "Não acho que" takes subjunctive.',
      examples: [
        { portuguese: 'Acho que ele vai vir.', spanish: 'Creo que él va a venir.' },
        { portuguese: 'Não acho que ele venha.', spanish: 'No creo que él venga.' },
        { portuguese: 'É importante que você saiba.', spanish: 'Es importante que tú sepas.' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'O que você acha da nova lei?', spanish: '¿Qué piensas de la nueva ley?' },
      { speaker: 'B', portuguese: 'Acho que é necessária, mas poderia ser melhor.', spanish: 'Creo que es necesaria, pero podría ser mejor.' },
      { speaker: 'A', portuguese: 'Concordo. Na minha opinião, falta informação.', spanish: 'De acuerdo. En mi opinión, falta información.' },
      { speaker: 'B', portuguese: 'Você tem razão. Depende de como for implementada.', spanish: 'Tienes razón. Depende de cómo sea implementada.' },
      { speaker: 'A', portuguese: 'Com certeza. Espero que melhore.', spanish: 'Con certeza. Espero que mejore.' },
    ],
    pronunciationTips: [
      { sound: 'razão', phonetic: '"hah-ZAUN"', example: 'razão → reason', tip: 'The "r" at the start sounds like English H. "Razão" = "hah-ZAUN." Also: rio, rua, rato.' },
      { sound: 'acho', phonetic: '"AH-shoh"', example: 'acho → I think', tip: '"Ch" in Portuguese sounds like English "sh." Acho, chá (tea), chocolate, China.' },
    ],
    quiz: [
      { question: 'The most common way to say "I think that..." in Brazil is:', options: ['Penso que...', 'Acho que...', 'Acredito que...', 'Considero que...'], correct: 1, explanation: '"Acho que" is used constantly in casual Brazilian speech — much more than "penso que."' },
      { question: '"Tem razão" means:', options: ['You\'re wrong', 'You\'re right', 'I agree', 'I disagree'], correct: 1, explanation: '"Ter razão" = to be right (literally "to have reason"), same logic as Spanish "tener razón."' },
      { question: '"Ch" in Portuguese sounds like:', options: ['k', 'ch (church)', 'sh (ship)', 'h (hat)'], correct: 2, explanation: '"Ch" in Portuguese sounds like English "sh" — acho, chá, chocolate, chave.' },
    ],
    speakingChallenge: 'Give your opinion on a current topic (sports, food, travel) in 4-5 sentences using Portuguese opinion expressions.',
    vocabulary: [
      { word: 'achar', translation: 'creer/pensar' }, { word: 'concordar', translation: 'estar de acuerdo' },
      { word: 'razão', translation: 'razón' }, { word: 'certeza', translation: 'certeza' },
      { word: 'depende', translation: 'depende' }, { word: 'opinião', translation: 'opinión' },
    ],
  },
  {
    id: 10,
    title: 'Viagem e Turismo',
    titleEs: 'Viaje y Turismo',
    level: 'A2',
    description: 'Travel Brazil with confidence — hotels, airports, tourist attractions and emergencies.',
    estimatedMinutes: 14,
    phrases: [
      { portuguese: 'Tenho uma reserva', spanish: 'Tengo una reserva', phonetic: 'TEN-yoh OO-mah heh-ZER-vah', example: 'Tenho uma reserva no nome de Silva.', nativeUsage: 'Checking into a hotel.' },
      { portuguese: 'O check-in é às que horas?', spanish: '¿A qué hora es el check-in?', phonetic: 'oh SHEK-een', example: 'O check-in é às 14h?', nativeUsage: 'Hotel vocabulary. Many English words are used as-is in Brazilian hotels.' },
      { portuguese: 'Minha bagagem foi perdida', spanish: 'Mi equipaje se perdió', phonetic: 'bah-ZHAH-jehn foy per-JEE-dah', example: 'Minha bagagem foi perdida na conexão.', nativeUsage: 'Reporting lost luggage at airport.' },
      { portuguese: 'Tem Wi-Fi no quarto?', spanish: '¿Hay Wi-Fi en la habitación?', phonetic: 'WEE-fee noh KWAHR-toh', example: 'Tem Wi-Fi gratuito no quarto?', nativeUsage: 'Essential modern travel question!' },
      { portuguese: 'Preciso de ajuda!', spanish: '¡Necesito ayuda!', phonetic: 'preh-SEE-zoh jee ah-ZHOO-dah', example: 'Com licença, preciso de ajuda!', nativeUsage: 'Emergency help request.' },
      { portuguese: 'O que vale a pena ver?', spanish: '¿Qué vale la pena ver?', phonetic: 'oh kee VAH-lee ah PEH-nah', example: 'O que vale a pena ver em Salvador?', nativeUsage: 'Ask for tourist recommendations.' },
    ],
    grammar: {
      title: 'Passive Voice with "Foi" + Past Participle',
      explanation: 'The passive voice in Portuguese mirrors Spanish closely. "Foi" (was) + past participle creates simple past passive constructions, frequently used in formal contexts.',
      examples: [
        { portuguese: 'Minha mala foi perdida.', spanish: 'Mi maleta fue perdida.' },
        { portuguese: 'O voo foi cancelado.', spanish: 'El vuelo fue cancelado.' },
        { portuguese: 'O hotel foi construído em 1920.', spanish: 'El hotel fue construido en 1920.' },
      ],
    },
    dialogue: [
      { speaker: 'A', portuguese: 'Boa tarde. Tenho uma reserva no nome de Oliveira.', spanish: 'Buenas tardes. Tengo una reserva a nombre de Oliveira.' },
      { speaker: 'B', portuguese: 'Encontrei aqui. Vai ficar quantas noites?', spanish: 'Lo encontré aquí. ¿Cuántas noches se va a quedar?' },
      { speaker: 'A', portuguese: 'Três noites. O quarto tem vista para o mar?', spanish: 'Tres noches. ¿La habitación tiene vista al mar?' },
      { speaker: 'B', portuguese: 'Sim! Quarto 412. O café da manhã está incluído.', spanish: 'Sí. Habitación 412. El desayuno está incluido.' },
      { speaker: 'A', portuguese: 'Ótimo! O que vale a pena ver por aqui?', spanish: '¡Excelente! ¿Qué vale la pena ver por aquí?' },
    ],
    pronunciationTips: [
      { sound: 'bagagem', phonetic: '"bah-ZHAH-jehn"', example: 'bagagem → luggage', tip: '"G" before e/i in Portuguese sounds like French "j" — like the "s" in "measure." Bagagem, gente, viagem.' },
      { sound: 'quarto', phonetic: '"KWAHR-toh"', example: 'quarto → room/fourth', tip: '"Qu" before "a/o" sounds like "kw" — quarto, quando, qualidade. Same as Spanish.' },
    ],
    quiz: [
      { question: '"Bagagem" means:', options: ['Bathroom', 'Luggage', 'Ticket', 'Passport'], correct: 1, explanation: '"Bagagem" = luggage/baggage. Similar to Spanish "bagaje" (though "equipaje" is more common in Spanish).' },
      { question: 'How do you say "breakfast is included"?', options: ['O café está incluso', 'O café da manhã está incluído', 'O jantar está incluído', 'O almoço está incluso'], correct: 1, explanation: '"Café da manhã" = breakfast (literally "morning coffee"). A key Brazilian expression.' },
      { question: '"G" before "e" and "i" in Portuguese sounds like:', options: ['Hard G (as in "go")', 'H sound', 'French J / English "zh"', 'K sound'], correct: 2, explanation: '"G" before e/i = soft, like French "j" or English "zh." Gente, viagem, bagagem.' },
    ],
    speakingChallenge: 'You\'re checking into a hotel in Rio de Janeiro. Handle the full conversation — reservation, room type, breakfast, and local recommendations.',
    vocabulary: [
      { word: 'viagem', translation: 'viaje' }, { word: 'quarto', translation: 'habitación' },
      { word: 'bagagem', translation: 'equipaje' }, { word: 'reserva', translation: 'reserva' },
      { word: 'aeroporto', translation: 'aeropuerto' }, { word: 'passaporte', translation: 'pasaporte' },
    ],
  },
];

export const getLessonById = (id: number): Lesson | undefined =>
  LESSONS.find((l) => l.id === id);

export const getLessonsByLevel = (level: string): Lesson[] =>
  LESSONS.filter((l) => l.level === level);

export const LEVEL_ORDER: Record<string, number> = { A0: 0, A1: 1, A2: 2, B1: 3 };

export const getNextLevel = (current: string): string => {
  const order = ['A0', 'A1', 'A2', 'B1'];
  const idx = order.indexOf(current);
  return idx < order.length - 1 ? order[idx + 1] : 'B1';
};
